version: "3.9"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]
  app:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - CHAT_HISTORY_LIMIT=50
    ports: ["8000:8000"]
    depends_on: [redis]
